name: Update

on: push

jobs:
  update:
    name: Check for updates

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
        bundler-cache: true
    - name: Unset bundler deployment
      run: bundle config unset deployment
    - name: Update Changelog
      run: |
        eval "$(bundle outdated |
        grep rubocop |
        awk '{print "sed -i \"2i* Update "$1" from "$2" to ["$3"](https://github.com/rubocop/"$1"/tag/v"$3")\" CHANGELOG.md"}' - )";
        sed -i '2i\\n## Unreleased\n' CHANGELOG.md;
    - name: Update Gemspec
      run: |
        eval "$(bundle outdated |
        grep rubocop |
        awk '{print "sed -i /\"" $1 "\"/s/" $2 "/" $3 "/ standard.gemspec"}' - )"
    - name: Update Gemfile
      run: bundle update
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        reviewers: camilopayan
        commit-message: '[ ${{ steps.date.outputs.date }} ] - Update dependencies'
        title: '[ ${{ steps.date.outputs.date }} ] - Update dependencies'
        delete-branch: true
        branch: update-deps-${{ steps.date.outputs.date }}
