name: Update

on: push

jobs:
  update:
    name: Check for updates

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
        bundler-cache: true
    - name: Unset deployment
      run: bundle config unset deployment
    - name: Update Gemspec
      run: |
        eval "$(bundle outdated |
        grep rubocop |
        awk '{print "sed -i /\"" $1 "\"/s/" $2 "/" $3 "/ standard.gemspec"}' - )"
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        reviewers: camilopayan
        commit-message: '[ ${{ steps.date.outputs.date }} ] - Update dependencies'
        title: '[ ${{ steps.date.outputs.date }} ] - Update dependencies'
        delete-branch: true
        branch: update-deps-${{ steps.date.outputs.date }}
